import { createHash } from 'crypto';

export const HEADER_PREFIX = '# ==============================================================================';
export const DO_NOT_EDIT_TEXT = '# THIS FILE IS AUTOMATICALLY GENERATED BY SDCTL. DO NOT EDIT DIRECTLY.';

export function calculateContentHash(content: string): string {
  // Strip existing header lines if present to hash pure body
  const lines = content.split('\n');
  const bodyLines = lines.filter(
    (line) =>
      !line.startsWith('# THIS FILE IS AUTOMATICALLY GENERATED') &&
      !line.startsWith('# Hash: ') &&
      !line.startsWith('# Generated at: ') &&
      !line.startsWith('# =============================================================================='),
  );
  return createHash('sha256').update(bodyLines.join('\n').trim()).digest('hex');
}

export function generateHeader(commentPrefix: string = '#'): string {
  return [
    `${commentPrefix} ==============================================================================`,
    `${commentPrefix} THIS FILE IS AUTOMATICALLY GENERATED BY SDCTL. DO NOT EDIT DIRECTLY.`,
    `${commentPrefix} Changes should be made to deployment.yaml and re-applied with \`sdctl apply\`.`,
    `${commentPrefix} ==============================================================================`,
    '',
  ].join('\n');
}

export function isManuallyModified(existingContent: string, newlyGeneratedContent: string): boolean {
  if (!existingContent.includes('THIS FILE IS AUTOMATICALLY GENERATED BY SDCTL')) {
    return true; // File wasn't generated by sdctl or header was removed
  }
  const existingHash = calculateContentHash(existingContent);
  const newHash = calculateContentHash(newlyGeneratedContent);
  return existingHash !== newHash;
}
