import type { SrdTemplateId } from './srdTypes';

/**
 * What the template picker shows: each template's name, description and
 * thumbnail. Kept apart from the PDF engine's registry (which draws the
 * templates) so the picker does not pull react-pdf into the view's bundle.
 * Keyed by SrdTemplateId, so a template missing here does not compile.
 */
export interface SrdTemplateInfo {
  id: SrdTemplateId;
  name: string;
  description: string;
}

export const SRD_TEMPLATE_CATALOG: Record<SrdTemplateId, SrdTemplateInfo> = {
  classic: {
    id: 'classic',
    name: 'Classic',
    description: 'One column, numbered headings with an accent rule, ruled tables.',
  },
  engineering: {
    id: 'engineering',
    name: 'Engineering',
    description: 'A specification: title band, each section on its own pages.',
  },
  briefing: {
    id: 'briefing',
    name: 'Briefing',
    description: 'A sidebar with the title and key metrics; sections beside it.',
  },
};

/**
 * A template's thumbnail, served from public/srd-templates/ (generated by
 * scripts/generate-srd-template-thumbnails.ts). A plain URL rather than an
 * imported asset, so modules showing it also load outside a bundler.
 */
export function templateThumbnailUrl(id: SrdTemplateId): string {
  const base = (import.meta as { env?: { BASE_URL?: string } }).env?.BASE_URL ?? '/';
  return `${base}srd-templates/${id}.png`;
}
