import type {Config} from '../config/schema.ts';
import {type Derived, type Route, upstreamOf} from '../config/derive.ts';

/**
 * bundled  — Caddy terminates TLS itself (HTTP-01, or DNS-01 through Cloudflare).
 * tunnel   — plain HTTP behind cloudflared; Cloudflare terminates TLS, so
 *            forwarded headers from the tunnel must be trusted.
 * snippet  — for an operator's own Caddy; upstreams are host:port.
 */
export type CaddyMode = 'bundled' | 'tunnel' | 'snippet';

const T = '\t';

export function renderCaddyfile(c: Config, d: Derived, mode: CaddyMode): string {
  const out: string[] = [
    '# Generated by system-design-installer. Changes made here are detected on the next run.',
  ];
  if (mode === 'snippet') {
    out.push(
        '# Paste these site blocks into your own Caddyfile. Upstreams point at the',
        '# ports this host publishes; make sure your proxy host can reach them.',
    );
  }
  out.push('');

  const global = globalOptions(c, mode);
  if (global.length) out.push('{', ...global.map((l) => T + l), '}', '');

  for (const host of d.hosts) {
    const routes = d.routes.filter((r) => r.host === host);
    const address = mode === 'tunnel' ? `http://${host}` : host;
    out.push(`${address} {`);
    out.push(...tlsBlock(c, mode).map((l) => (l ? T + l : l)));
    out.push(
        `${T}header {`,
        `${T}${T}Strict-Transport-Security "max-age=31536000; includeSubDomains"`,
        `${T}${T}X-Content-Type-Options "nosniff"`,
        `${T}${T}X-Frame-Options "SAMEORIGIN"`,
        `${T}${T}Referrer-Policy "strict-origin-when-cross-origin"`,
        `${T}${T}-Server`,
        `${T}}`,
        '',
    );
    if (d.rootRedirect?.host === host) {
      out.push(`${T}redir / ${d.rootRedirect.to} 302`, '');
    }
    for (const r of routes) out.push(...routeBlock(c, r).map((l) => (l ? T + l : l)));
    if (routes.every((r) => r.prefix !== '')) {
      out.push(`${T}handle {`, `${T}${T}respond "Not found" 404`, `${T}}`);
    }
    out.push('}', '');
  }
  return out.join('\n');
}

function globalOptions(c: Config, mode: CaddyMode): string[] {
  if (mode === 'tunnel') {
    return [
      'auto_https off',
      'servers {',
      // cloudflared reaches us over the compose network; trust its X-Forwarded-*
      // so Keycloak and the store see https rather than http.
      '\ttrusted_proxies static private_ranges',
      '}',
    ];
  }
  if (mode === 'bundled' && c.proxy.type === 'caddy' && c.proxy.email)
    return [`email ${c.proxy.email}`];
  return [];
}

function tlsBlock(c: Config, mode: CaddyMode): string[] {
  if (mode === 'snippet') {
    return ['# For DNS-01 through Cloudflare, add a tls { dns cloudflare … } block here.', ''];
  }
  if (mode !== 'bundled' || c.proxy.type !== 'caddy' || c.proxy.acme !== 'cloudflare-dns')
    return [];
  const p = c.proxy;
  const lines = ['tls {', '\tdns cloudflare {env.CLOUDFLARE_API_TOKEN}'];
  if (p.resolvers?.length) lines.push(`\tresolvers ${p.resolvers.join(' ')}`);
  if (p.propagationDelay) lines.push(`\tpropagation_delay ${p.propagationDelay}`);
  if (p.propagationTimeout) lines.push(`\tpropagation_timeout ${p.propagationTimeout}`);
  lines.push('}', '');
  return lines;
}

function routeBlock(c: Config, r: Route): string[] {
  const upstream = upstreamOf(c, r);
  const proxy = r.websocket
      ? [`reverse_proxy ${upstream} {`, '\tflush_interval -1', '}']
      : [`reverse_proxy ${upstream}`];

  if (r.prefix === '') {
    return [`# ${r.id}`, 'handle {', ...proxy.map((l) => '\t' + l), '}', ''];
  }
  const name = `@${r.id}`;
  const lines = [`# ${r.id}`];
  // A bare /editor would resolve the SPA's relative asset paths against "/".
  if (r.id === 'editor') lines.push(`redir ${r.prefix} ${r.prefix}/?{query} 308`);
  lines.push(`${name} path ${r.prefix} ${r.prefix}/*`, `handle ${name} {`);
  if (r.strip) lines.push(`\turi strip_prefix ${r.prefix}`);
  lines.push(...proxy.map((l) => '\t' + l), '}', '');
  return lines;
}

/**
 * The app's routes as a named snippet, for a Caddyfile the operator owns.
 * Every route carries a host matcher, so the snippet can sit inside a
 * wildcard site block alongside unrelated services.
 */
export function renderCaddySnippet(c: Config, d: Derived): string {
  const out = [
    '# Generated by system-design-installer and replaced on every run: edit Caddyfile, not this.',
    '# Caddyfile imports this file once at the top level (import system-design.caddy) and uses',
    `# "import system-design" inside the site block(s) serving ${d.hosts.join(', ')}.`,
    '',
    '(system-design) {',
  ];
  const matcher = (name: string, host: string, paths?: string) =>
      paths
          ? [`@${name} {`, `${T}host ${host}`, `${T}path ${paths}`, '}']
          : [`@${name} host ${host}`];
  const body: string[] = [];
  if (d.rootRedirect)
    body.push(
        ...matcher('sd_root', d.rootRedirect.host, '/'),
        `redir @sd_root ${d.rootRedirect.to} 302`,
        '',
    );
  for (const r of d.routes) {
    const name = `sd_${r.id}`;
    const upstream = upstreamOf(c, r);
    const proxy = r.websocket
        ? [`reverse_proxy ${upstream} {`, `${T}flush_interval -1`, '}']
        : [`reverse_proxy ${upstream}`];
    body.push(`# ${r.id}`);
    if (r.id === 'editor' && r.prefix)
      body.push(
          ...matcher('sd_editor_bare', r.host, r.prefix),
          `redir @sd_editor_bare ${r.prefix}/?{query} 308`,
      );
    body.push(
        ...matcher(name, r.host, r.prefix ? `${r.prefix} ${r.prefix}/*` : undefined),
        `handle @${name} {`,
    );
    if (r.strip) body.push(`${T}uri strip_prefix ${r.prefix}`);
    body.push(...proxy.map((l) => T + l), '}', '');
  }
  out.push(...body.map((l) => (l ? T + l : l)));
  while (out.at(-1) === '') out.pop();
  out.push('}', '');
  return out.join('\n');
}

/**
 * The first version of an operator-owned Caddyfile: written once if none
 * exists, then never touched again.
 */
export function renderSharedCaddyfileSeed(c: Config, d: Derived): string {
  const out = [
    '# This Caddyfile is yours. The installer created it once and will not change it;',
    '# it maintains system-design.caddy beside it. Keep both imports below.',
    '# After editing, apply with:  <installer> proxy-reload',
    '',
  ];
  const global = globalOptions(c, 'bundled');
  if (global.length) out.push('{', ...global.map((l) => T + l), '}', '');
  out.push('import system-design.caddy', '', `${d.hosts.join(', ')} {`);
  out.push(...tlsBlock(c, 'bundled').map((l) => (l ? T + l : l)));
  out.push(
      `${T}header {`,
      `${T}${T}Strict-Transport-Security "max-age=31536000; includeSubDomains"`,
      `${T}${T}X-Content-Type-Options "nosniff"`,
      `${T}${T}X-Frame-Options "SAMEORIGIN"`,
      `${T}${T}Referrer-Policy "strict-origin-when-cross-origin"`,
      `${T}${T}-Server`,
      `${T}}`,
      '',
      `${T}import system-design`,
      '}',
      '',
      '# Your other sites go here, for example:',
      '# other.example.com {',
      '# \treverse_proxy 192.168.1.10:8080',
      '# }',
      '',
  );
  return out.join('\n');
}

/** Image build for Caddy with the Cloudflare DNS module, used for DNS-01. */
export function renderCaddyDockerfile(c: Config): string {
  return [
    '# Generated by system-design-installer: Caddy with the Cloudflare DNS module.',
    `FROM ${c.images.caddyBuilder} AS builder`,
    'RUN xcaddy build --with github.com/caddy-dns/cloudflare',
    '',
    `FROM ${c.images.caddy}`,
    'COPY --from=builder /usr/bin/caddy /usr/bin/caddy',
    '',
  ].join('\n');
}
