import type {Config} from '../config/schema.ts';
import {type Derived, type Route, upstreamOf} from '../config/derive.ts';

/**
 * bundled  — Caddy terminates TLS itself (HTTP-01, or DNS-01 through Cloudflare).
 * tunnel   — plain HTTP behind cloudflared; Cloudflare terminates TLS, so
 *            forwarded headers from the tunnel must be trusted.
 * snippet  — for an operator's own Caddy; upstreams are host:port.
 */
export type CaddyMode = 'bundled' | 'tunnel' | 'snippet';

const T = '\t';

export function renderCaddyfile(c: Config, d: Derived, mode: CaddyMode): string {
    const out: string[] = [
        '# Generated by system-design-installer. Changes made here are detected on the next run.',
    ];
    if (mode === 'snippet') {
        out.push(
            '# Paste these site blocks into your own Caddyfile. Upstreams point at the',
            '# ports this host publishes; make sure your proxy host can reach them.',
        );
    }
    out.push('');

    const global = globalOptions(c, mode);
    if (global.length) out.push('{', ...global.map((l) => T + l), '}', '');

    for (const host of d.hosts) {
        const routes = d.routes.filter((r) => r.host === host);
        const address = mode === 'tunnel' ? `http://${host}` : host;
        out.push(`${address} {`);
        out.push(...tlsBlock(c, mode).map((l) => (l ? T + l : l)));
        out.push(
            `${T}header {`,
            `${T}${T}Strict-Transport-Security "max-age=31536000; includeSubDomains"`,
            `${T}${T}X-Content-Type-Options "nosniff"`,
            `${T}${T}X-Frame-Options "SAMEORIGIN"`,
            `${T}${T}Referrer-Policy "strict-origin-when-cross-origin"`,
            `${T}${T}-Server`,
            `${T}}`,
            '',
        );
        if (d.rootRedirect?.host === host) {
            out.push(`${T}redir / ${d.rootRedirect.to} 302`, '');
        }
        for (const r of routes) out.push(...routeBlock(c, r).map((l) => (l ? T + l : l)));
        if (routes.every((r) => r.prefix !== '')) {
            out.push(`${T}handle {`, `${T}${T}respond "Not found" 404`, `${T}}`);
        }
        out.push('}', '');
    }
    return out.join('\n');
}

function globalOptions(c: Config, mode: CaddyMode): string[] {
    if (mode === 'tunnel') {
        return [
            'auto_https off',
            'servers {',
            // cloudflared reaches us over the compose network; trust its X-Forwarded-*
            // so Keycloak and the store see https rather than http.
            '\ttrusted_proxies static private_ranges',
            '}',
        ];
    }
    if (mode === 'bundled' && c.proxy.type === 'caddy' && c.proxy.email) return [`email ${c.proxy.email}`];
    return [];
}

function tlsBlock(c: Config, mode: CaddyMode): string[] {
    if (mode === 'snippet') {
        return ['# For DNS-01 through Cloudflare, add a tls { dns cloudflare … } block here.', ''];
    }
    if (mode !== 'bundled' || c.proxy.type !== 'caddy' || c.proxy.acme !== 'cloudflare-dns') return [];
    const p = c.proxy;
    const lines = ['tls {', '\tdns cloudflare {env.CLOUDFLARE_API_TOKEN}'];
    if (p.resolvers?.length) lines.push(`\tresolvers ${p.resolvers.join(' ')}`);
    if (p.propagationDelay) lines.push(`\tpropagation_delay ${p.propagationDelay}`);
    if (p.propagationTimeout) lines.push(`\tpropagation_timeout ${p.propagationTimeout}`);
    lines.push('}', '');
    return lines;
}

function routeBlock(c: Config, r: Route): string[] {
    const upstream = upstreamOf(c, r);
    const proxy = r.websocket
        ? [`reverse_proxy ${upstream} {`, '\tflush_interval -1', '}']
        : [`reverse_proxy ${upstream}`];

    if (r.prefix === '') {
        return [`# ${r.id}`, 'handle {', ...proxy.map((l) => '\t' + l), '}', ''];
    }
    const name = `@${r.id}`;
    const lines = [`# ${r.id}`];
    // A bare /editor would resolve the SPA's relative asset paths against "/".
    if (r.id === 'editor') lines.push(`redir ${r.prefix} ${r.prefix}/?{query} 308`);
    lines.push(`${name} path ${r.prefix} ${r.prefix}/*`, `handle ${name} {`);
    if (r.strip) lines.push(`\turi strip_prefix ${r.prefix}`);
    lines.push(...proxy.map((l) => '\t' + l), '}', '');
    return lines;
}

/** Image build for Caddy with the Cloudflare DNS module, used for DNS-01. */
export function renderCaddyDockerfile(c: Config): string {
    return [
        '# Generated by system-design-installer: Caddy with the Cloudflare DNS module.',
        `FROM ${c.images.caddyBuilder} AS builder`,
        'RUN xcaddy build --with github.com/caddy-dns/cloudflare',
        '',
        `FROM ${c.images.caddy}`,
        'COPY --from=builder /usr/bin/caddy /usr/bin/caddy',
        '',
    ].join('\n');
}
