import type {Config} from '../config/schema.ts';
import {derive, type Derived} from '../config/derive.ts';
import {formatEnvValue, type Secrets, secretSpecs} from '../config/secrets.ts';
import {renderCompose} from './compose.ts';
import {renderCaddyDockerfile, renderCaddyfile, renderCaddySnippet, renderSharedCaddyfileSeed,} from './caddy.ts';
import {renderNginx} from './nginx.ts';

export interface RenderedFile {
    /** Relative to the install directory. */
    path: string;
    content: string;
    mode?: number;
    /** Holds secrets: masked in diffs, written 0600. */
    secret?: boolean;
    /** Written only when absent and never tracked: the operator owns it afterwards. */
    seed?: boolean;
}

export interface ImageRefs {
    editor: string;
    relay: string;
    store: string;
}

export interface RenderInput {
    config: Config;
    secrets: Secrets;
    images: ImageRefs;
}

export function renderAll({config: c, secrets, images}: RenderInput): RenderedFile[] {
    const d = derive(c);
    const files: RenderedFile[] = [
        {path: 'compose.yml', content: renderCompose(c, d)},
        {path: '.env', content: renderEnv(c, secrets, images), mode: 0o600, secret: true},
    ];

    const p = c.proxy;
    if (p.type === 'caddy') {
        if (p.shared) {
            files.push(
                {path: 'caddy/system-design.caddy', content: renderCaddySnippet(c, d)},
                {path: 'caddy/Caddyfile', content: renderSharedCaddyfileSeed(c, d), seed: true},
            );
        } else {
            files.push({path: 'Caddyfile', content: renderCaddyfile(c, d, 'bundled')});
        }
        if (p.acme === 'cloudflare-dns' && p.build)
            files.push({path: 'caddy/Dockerfile', content: renderCaddyDockerfile(c)});
    } else if (p.type === 'nginx') {
        files.push({path: 'nginx/default.conf', content: renderNginx(c, d, 'bundled')});
        if (p.tls === 'certbot-cloudflare') {
            files.push({
                path: 'certbot/conf/cloudflare.ini',
                content: `# Generated by system-design-installer.\ndns_cloudflare_api_token = ${secrets.CLOUDFLARE_API_TOKEN}\n`,
                mode: 0o600,
                secret: true,
            });
        }
    } else if (p.type === 'cloudflare-tunnel') {
        files.push({path: 'Caddyfile', content: renderCaddyfile(c, d, 'tunnel')});
    } else {
        files.push(
            {path: 'proxy-snippets/Caddyfile', content: renderCaddyfile(c, d, 'snippet')},
            {path: 'proxy-snippets/nginx.conf', content: renderNginx(c, d, 'snippet')},
        );
    }

    if (c.identity.type === 'keycloak')
        files.push({path: 'keycloak-realm.json', content: renderRealm(c, d)});
    if (c.turn.type === 'bundled') files.push({path: 'turnserver.conf', content: renderTurn(c)});
    return files;
}

export function renderEnv(c: Config, secrets: Secrets, images: ImageRefs): string {
    const lines = [
        '# Generated by system-design-installer.',
        '# This file is the source of truth for secrets: back it up, keep it private.',
        '',
        '# Image references; `upgrade` and `rollback` change these.',
        `EDITOR_IMAGE=${formatEnvValue(images.editor)}`,
        `RELAY_IMAGE=${formatEnvValue(images.relay)}`,
        `STORE_IMAGE=${formatEnvValue(images.store)}`,
        '',
        '# Secrets',
    ];
    for (const spec of secretSpecs(c)) {
        const v = secrets[spec.env];
        if (v !== undefined) lines.push(`${spec.env}=${formatEnvValue(v)}`);
    }
    return lines.join('\n') + '\n';
}

export function renderRealm(c: Config, d: Derived): string {
    if (c.identity.type !== 'keycloak') throw new Error('realm requested without keycloak');
    const i = c.identity;
    const origins = [...new Set([new URL(d.editorUrl).origin, new URL(d.storeUrl).origin])];
    const realm = {
        realm: i.realm,
        enabled: true,
        sslRequired: 'external',
        registrationAllowed: false,
        clients: [
            {
                clientId: i.clientId,
                name: 'Engineers Notebook Workspace',
                enabled: true,
                protocol: 'openid-connect',
                publicClient: false,
                // Keycloak substitutes this from its environment at import, so the
                // secret never sits in this file.
                secret: '${OIDC_CLIENT_SECRET}',
                standardFlowEnabled: true,
                directAccessGrantsEnabled: false,
                serviceAccountsEnabled: false,
                redirectUris: [`${d.storeUrl}/v1/auth/callback`],
                webOrigins: origins,
                attributes: {'pkce.code.challenge.method': 'S256'},
                protocolMappers: [
                    {
                        name: 'groups',
                        protocol: 'openid-connect',
                        protocolMapper: 'oidc-group-membership-mapper',
                        consentRequired: false,
                        config: {
                            'claim.name': 'groups',
                            'full.path': 'true',
                            'id.token.claim': 'true',
                            'access.token.claim': 'false',
                            'userinfo.token.claim': 'true',
                            'introspection.token.claim': 'true',
                        },
                    },
                ],
            },
        ],
        groups: i.groups.map((name) => ({name})),
    };
    return JSON.stringify(realm, null, 2) + '\n';
}

/** Address space TURN must not relay into unless the operator allows it. */
const PRIVATE_RANGES = [
    '0.0.0.0-0.255.255.255',
    '10.0.0.0-10.255.255.255',
    '100.64.0.0-100.127.255.255',
    '127.0.0.0-127.255.255.255',
    '169.254.0.0-169.254.255.255',
    '172.16.0.0-172.31.255.255',
    '192.168.0.0-192.168.255.255',
    '::1',
    'fc00::-fdff:ffff:ffff:ffff:ffff:ffff:ffff:ffff',
    'fe80::-febf:ffff:ffff:ffff:ffff:ffff:ffff:ffff',
];

export function renderTurn(c: Config): string {
    if (c.turn.type !== 'bundled') throw new Error('turn config requested without bundled turn');
    const t = c.turn;
    const lines = [
        '# Generated by system-design-installer.',
        '# The long-term credential is passed on the command line from .env (TURN_PASSWORD).',
        `listening-port=${t.port}`,
        'fingerprint',
        'lt-cred-mech',
        `realm=${t.host}`,
        `min-port=${t.minPort}`,
        `max-port=${t.maxPort}`,
        // Browsers reach TURN over plain UDP/TCP here; the media itself is DTLS-encrypted end to end.
        'no-tls',
        'no-dtls',
        'no-cli',
        'no-multicast-peers',
    ];
    if (t.externalIp) lines.push(`external-ip=${t.externalIp}`);
    if (t.denyPrivatePeers) lines.push(...PRIVATE_RANGES.map((r) => `denied-peer-ip=${r}`));
    lines.push('log-file=stdout', 'simple-log');
    return lines.join('\n') + '\n';
}
