import type {Config} from '../config/schema.ts';
import {type Derived, type Route, upstreamOf} from '../config/derive.ts';

export type NginxMode = 'bundled' | 'snippet';

/** Certificate name certbot uses; one certificate covers every host. */
export function certName(c: Config): string {
    return c.project;
}

export function certPaths(c: Config): { cert: string; key: string } {
    if (c.proxy.type === 'nginx' && c.proxy.tls === 'provided') {
        return {cert: '/etc/nginx/certs/fullchain.pem', key: '/etc/nginx/certs/privkey.pem'};
    }
    return {
        cert: `/etc/letsencrypt/live/${certName(c)}/fullchain.pem`,
        key: `/etc/letsencrypt/live/${certName(c)}/privkey.pem`,
    };
}

const I = '    ';

export function renderNginx(c: Config, d: Derived, mode: NginxMode): string {
    const out: string[] = ['# Generated by system-design-installer. Changes made here are detected on the next run.'];
    if (mode === 'snippet') {
        out.push(
            '# For your own nginx: place in conf.d/ (or an http {} block) and set the',
            '# certificate paths. Upstreams point at the ports this host publishes.',
        );
    }
    out.push(
        '',
        'map $http_upgrade $connection_upgrade {',
        `${I}default upgrade;`,
        `${I}''      close;`,
        '}',
        '',
        'server {',
        `${I}listen 80;`,
        `${I}server_name ${d.hosts.join(' ')};`,
        `${I}server_tokens off;`,
    );
    if (mode === 'bundled') {
        out.push(`${I}location /.well-known/acme-challenge/ {`, `${I}${I}root /var/www/certbot;`, `${I}}`);
    }
    out.push(`${I}location / {`, `${I}${I}return 301 https://$host$request_uri;`, `${I}}`, '}', '');

    const certs = mode === 'bundled' ? certPaths(c) : {
        cert: '/etc/ssl/CHANGE-ME/fullchain.pem',
        key: '/etc/ssl/CHANGE-ME/privkey.pem'
    };

    for (const host of d.hosts) {
        const routes = d.routes.filter((r) => r.host === host);
        out.push(
            'server {',
            `${I}listen 443 ssl;`,
            `${I}http2 on;`,
            `${I}server_name ${host};`,
            `${I}server_tokens off;`,
            '',
            `${I}ssl_certificate     ${certs.cert};`,
            `${I}ssl_certificate_key ${certs.key};`,
            `${I}ssl_protocols TLSv1.2 TLSv1.3;`,
            `${I}ssl_session_cache shared:SSL:10m;`,
            '',
            // The store's default blob limit is 8 MB; leave headroom for envelopes.
            `${I}client_max_body_size 64m;`,
            '',
            `${I}add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;`,
            `${I}add_header X-Content-Type-Options "nosniff" always;`,
            `${I}add_header X-Frame-Options "SAMEORIGIN" always;`,
            `${I}add_header Referrer-Policy "strict-origin-when-cross-origin" always;`,
            '',
        );
        if (d.rootRedirect?.host === host) {
            out.push(`${I}location = / {`, `${I}${I}return 302 ${d.rootRedirect.to};`, `${I}}`, '');
        }
        for (const r of routes) out.push(...locationBlocks(c, r));
        if (routes.every((r) => r.prefix !== '')) {
            out.push(`${I}location / {`, `${I}${I}return 404;`, `${I}}`);
        }
        out.push('}', '');
    }
    return out.join('\n');
}

function proxyDirectives(r: Route): string[] {
    const lines = [
        'proxy_http_version 1.1;',
        'proxy_set_header Host $host;',
        'proxy_set_header X-Real-IP $remote_addr;',
        'proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;',
        'proxy_set_header X-Forwarded-Proto $scheme;',
        'proxy_set_header X-Forwarded-Host $host;',
        'proxy_set_header X-Forwarded-Port $server_port;',
        'proxy_set_header Upgrade $http_upgrade;',
        'proxy_set_header Connection $connection_upgrade;',
    ];
    if (r.websocket) lines.push('proxy_buffering off;', 'proxy_read_timeout 1h;', 'proxy_send_timeout 1h;');
    // Keycloak's responses carry large cookies and headers.
    if (r.id === 'auth') lines.push('proxy_buffer_size 128k;', 'proxy_buffers 4 256k;', 'proxy_busy_buffers_size 256k;');
    return lines;
}

function location(match: string, pass: string, r: Route): string[] {
    return [
        `${I}location ${match} {`,
        `${I}${I}proxy_pass ${pass};`,
        ...proxyDirectives(r).map((l) => `${I}${I}${l}`),
        `${I}}`,
    ];
}

function locationBlocks(c: Config, r: Route): string[] {
    const up = `http://${upstreamOf(c, r)}`;
    const lines = [`${I}# ${r.id}`];
    if (r.prefix === '') {
        lines.push(...location('/', up, r), '');
        return lines;
    }
    const p = r.prefix;
    if (r.strip) {
        if (r.websocket) {
            // Clients connect to exactly wss://host/relay, so it must not redirect.
            lines.push(...location(`= ${p}`, `${up}/`, r));
        } else {
            lines.push(`${I}location = ${p} {`, `${I}${I}return 308 ${p}/$is_args$args;`, `${I}}`);
        }
        // A URI on proxy_pass replaces the matched prefix: /store/x -> /x.
        lines.push(...location(`${p}/`, `${up}/`, r));
    } else {
        lines.push(`${I}location = ${p} {`, `${I}${I}return 308 ${p}/;`, `${I}}`);
        lines.push(...location(`${p}/`, up, r));
    }
    lines.push('');
    return lines;
}
