import {existsSync, readFileSync} from 'node:fs';
import type {Config} from './schema.ts';
import {type Draft, getPath, InstallerError, randomSecret, setPath} from '../lib/util.ts';

export interface SecretSpec {
    /** Dotted path in the config holding the reference. */
    path: string;
    /** Variable name in .env. */
    env: string;
    /** Whether "generate" is allowed. Tokens issued by someone else are not. */
    generatable: boolean;
    /**
     * PostgreSQL reads its password only when the data directory is created.
     * Changing one of these later does not change the database's password,
     * so the installer refuses to do it silently.
     */
    initOnly?: boolean;
    /** Characters a value may contain, when it ends up inside a URL. */
    urlSafe?: boolean;
}

/** Every secret the installer knows about, given the configuration's shape. */
export function secretSpecs(c: Pick<Config, 'proxy' | 'identity' | 'turn'>): SecretSpec[] {
    const specs: SecretSpec[] = [
        {path: 'secrets.postgresPassword', env: 'POSTGRES_PASSWORD', generatable: true, initOnly: true, urlSafe: true},
        {path: 'secrets.relayTokenSecret', env: 'RELAY_TOKEN_SECRET', generatable: true},
    ];
    const p = c.proxy;
    if ((p.type === 'caddy' && p.acme === 'cloudflare-dns') || (p.type === 'nginx' && p.tls === 'certbot-cloudflare')) {
        specs.push({path: 'proxy.cloudflareApiToken', env: 'CLOUDFLARE_API_TOKEN', generatable: false});
    }
    if (p.type === 'cloudflare-tunnel') specs.push({path: 'proxy.token', env: 'TUNNEL_TOKEN', generatable: false});

    const i = c.identity;
    if (i.type === 'keycloak') {
        specs.push(
            {path: 'identity.adminPassword', env: 'KEYCLOAK_ADMIN_PASSWORD', generatable: true},
            {path: 'identity.dbPassword', env: 'KEYCLOAK_DB_PASSWORD', generatable: true, initOnly: true},
            {path: 'identity.clientSecret', env: 'OIDC_CLIENT_SECRET', generatable: true},
        );
    } else if (i.type === 'oidc') {
        specs.push({path: 'identity.clientSecret', env: 'OIDC_CLIENT_SECRET', generatable: false});
    } else {
        specs.push({path: 'identity.clientSecret', env: 'GITHUB_CLIENT_SECRET', generatable: false});
    }
    if (c.turn.type === 'bundled') specs.push({path: 'turn.password', env: 'TURN_PASSWORD', generatable: true});
    return specs;
}

export type Secrets = Record<string, string>;

export interface ResolvedSecrets {
    values: Secrets;
    /** Env names that were freshly generated by this run. */
    generated: string[];
    /** Env names whose value differs from what .env held. */
    changed: string[];
}

/**
 * Resolves every secret reference. Precedence: an explicit value (literal,
 * env:, file:) wins; otherwise the value already in .env; otherwise, if
 * allowed, a new random one. A database password is never replaced
 * without `allowInitOnlyChange`, because the database would keep the old one.
 */
export function resolveSecrets(
    config: Config,
    existingEnv: Record<string, string>,
    opts: { allowInitOnlyChange?: boolean; databasesExist?: boolean } = {},
): ResolvedSecrets {
    const out: ResolvedSecrets = {values: {}, generated: [], changed: []};
    for (const spec of secretSpecs(config)) {
        const ref = getPath(config, spec.path);
        const existing = existingEnv[spec.env];
        let value: string;
        if (ref === undefined || ref === 'generate' || ref === 'stored') {
            if (existing) value = existing;
            else if (ref === 'stored') {
                throw new InstallerError(`${spec.env} is expected in .env but is missing.`, `Set ${spec.path} in a manifest, or restore .env from a backup.`);
            } else if (spec.generatable) {
                value = randomSecret();
                out.generated.push(spec.env);
            } else {
                throw new InstallerError(`${spec.path} has no value and cannot be generated.`, 'Supply it in the manifest or answer the prompt.');
            }
        } else {
            value = dereference(String(ref), spec.path);
        }
        validateSecret(spec, value);
        if (existing && existing !== value) {
            if (spec.initOnly && opts.databasesExist && !opts.allowInitOnlyChange) {
                throw new InstallerError(
                    `${spec.env} differs from the value the database was created with.`,
                    'PostgreSQL only reads this on first start, so changing it here would lock the store out. ' +
                    'Change the password inside PostgreSQL first, then re-run with --force.',
                );
            }
            out.changed.push(spec.env);
        }
        out.values[spec.env] = value;
    }
    return out;
}

export function dereference(ref: string, label: string): string {
    if (ref.startsWith('env:')) {
        const name = ref.slice(4);
        const v = process.env[name];
        if (!v) throw new InstallerError(`${label} refers to environment variable ${name}, which is not set.`, `Pass it with docker run -e ${name}=…`);
        return v;
    }
    if (ref.startsWith('file:')) {
        const path = ref.slice(5);
        if (!existsSync(path)) throw new InstallerError(`${label} refers to ${path}, which does not exist inside the installer container.`, 'Mount it with -v.');
        return readFileSync(path, 'utf8').trim();
    }
    return ref;
}

function validateSecret(spec: SecretSpec, value: string): void {
    if (/[\r\n]/.test(value)) throw new InstallerError(`${spec.env} must be a single line.`);
    // .env values are single-quoted so compose takes them literally; a single
    // quote cannot be represented inside one.
    if (value.includes("'")) throw new InstallerError(`${spec.env} cannot contain a single quote (').`);
    if (spec.urlSafe && !/^[A-Za-z0-9._~-]+$/.test(value)) {
        throw new InstallerError(
            `${spec.env} is placed inside a database URL and may only contain letters, digits and . _ ~ -`,
            'Use "generate" to have one made for you.',
        );
    }
}

/** Replaces secret values in a config with "stored", for saving to config.yml. */
export function redactConfig(config: Config): Draft {
    const copy = structuredClone(config) as unknown as Draft;
    for (const spec of secretSpecs(config)) {
        if (getPath(copy, spec.path) !== undefined) setPath(copy, spec.path, 'stored');
    }
    return copy;
}

// ---------------------------------------------------------------- .env I/O

export function parseEnvFile(text: string): Record<string, string> {
    const out: Record<string, string> = {};
    for (const raw of text.split(/\r?\n/)) {
        const line = raw.trim();
        if (!line || line.startsWith('#')) continue;
        const eq = line.indexOf('=');
        if (eq < 1) continue;
        const key = line.slice(0, eq).trim().replace(/^export\s+/, '');
        let value = line.slice(eq + 1).trim();
        if ((value.startsWith("'") && value.endsWith("'")) || (value.startsWith('"') && value.endsWith('"'))) {
            value = value.slice(1, -1);
        }
        out[key] = value;
    }
    return out;
}

export function readEnvFile(path: string): Record<string, string> {
    return existsSync(path) ? parseEnvFile(readFileSync(path, 'utf8')) : {};
}

export function formatEnvValue(value: string): string {
    return `'${value}'`;
}
