services:
  editor:
    image: ghcr.io/jbraunsmajr/system-design:${EDITOR_VERSION:-latest}
    environment:
      VITE_SIGNALING_URL: ${RELAY_URL:-wss://relay.example.com}

      # The DNS entry that points to the host this editor is running on.
      APP_URL: ${EDITOR_URL:-https://editor.example.com}

      # Example from air-gapped network
      # ICE_SERVERS: ${ICE_SERVERS:-}
    container_name: system-design-editor
    hostname: editor
    restart: unless-stopped
    networks:
      - core

  relay:
    image: ghcr.io/jbraunsmajr/system-design-relay:${RELAY_VERSION:-latest}
    container_name: system-design-relay
    hostname: relay
    restart: unless-stopped
    networks:
      - core

  proxy:
    image: nginx:alpine
    container_name: system-design-proxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./certs:/etc/nginx/certs:ro"
    restart: unless-stopped
    depends_on:
      - relay
      - editor
    networks:
      - core

networks:
  core: