server {
    listen 443 ssl;
    server_name design.internal;

    # HTTPS for incoming traffic
    ssl_certificate /etc/nginx/certs/design.crt;
    ssl_certificate_key /etc/nginx/certs/design.key;

    # mTLS certificates
    proxy_ssl_certificate /etc/nginx/certs/design.crt;
    proxy_ssl_certificate_key /etc/nginx/certs/design.key;
    proxy_ssl_trusted_certificate /etc/nginx/ca.crt;
    proxy_ssl_verify on;

    # Self-signed certificates with single root CA e.g. Server Cert -> Root CA, so we set depth to 1
    # Increase depth or remove if intermediate are introduced
    proxy_ssl_verify_depth 1;

    # Relay specific traffic
    location /relay {
        proxy_pass "http://relay:4444/";
        proxy_http_version: 1.1;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Main Application
    location / {
        # Same network as relay
        proxy_pass "http://editor/";

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_redirect off;
    }
}